---
title: "Questionnaire"
author: "Peter von Rohr"
date: "2018-09-21"
output: html_notebook
---

This questionnaire helps me to assess your experience with programming and data analysis. It is not a test and it will not be graded. Please, answer the following question. Thank you very much for your collaboration. 

## Question 1
What programming languages do you know? For each programming language you know, please indicate the level of your knowledge with the labels _professional_ (p), _intermediate_ (m) and _beginner_ (b).

### Your Answer <!-- Please specify your answer, starting on the next line-->




## Question 2
Have you made any experiences with programming languages such as R in previous courses or projects?

### Your Answer <!-- Please specify your answer, starting on the next line-->




## Question 3
What tools do you use when you have to work with data during your internships/practicals or during your Bachelor or Master thesis?

### Your Answer <!-- Please specify your answer, starting on the next line-->




## Question 4
Are you interested in learning how to program? Please rate the level of your interest with the labels _very high_, _rather high_, _low_ and _very low_. 

### Your Answer <!-- Please specify your answer, starting on the next line-->


